# Generated by Django 5.0.6 on 2024-08-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_chatroom_chatmessage_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
