# Generated by Django 5.0.6 on 2024-08-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0010_alter_chatmessage_chat_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='realtime.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtime.chatroom'),
        ),
    ]
