# Generated by Django 5.0.6 on 2024-08-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.chatroom'),
        ),
    ]
