# Generated by Django 5.0.6 on 2024-09-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_friendship_delete_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='user_two',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user_one',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'reciever')},
        ),
    ]
