name: CI/CD 

on:
  push:
    branches:
      - master  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # The context for the Docker build (current directory)
          push: true
          tags: anwarmusthafa/momentus-web:latest

      - name: SSH to server and deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "."  # This transfers everything from the current directory. Modify if needed.
          target: "/home/ubuntu/momentus/"  # Ensure this matches the directory created on your EC2 instance

      - name: Restart Docker containers
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/momentus/ && \
            docker-compose -f /path/to/docker-compose.yml up -d --remove-orphans
          "

      - name: Cleanup
        run: |
          # Optionally clean up files if needed
          echo "Cleanup step (if needed)"
