name: CI/CD  

on:
  push:
    branches:
      - master  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # The context for the Docker build (current directory)
          push: true
          tags: anwarmusthafa/momentus-web:latest

      - name: Transfer project files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "."  # Transfer all files from the repository directory
          target: "/home/ubuntu/momentus/"  # Ensure this directory exists on your server

      - name: Restart Docker containers on the server
        run: |
          set -e  # Exit on any error
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/momentus/ && \
            docker-compose -f /home/ubuntu/momentus/docker-compose.yml up -d --remove-orphans
          "

      - name: Cleanup temporary files
        run: |
          rm -f private_key.pem  # Clean up the private key after use
